# Persistent Volume Claim for digitalocean block storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tor-relay-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
  storageClassName: do-block-storage

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: tor-relay
spec:
  selector:
    matchLabels:
      app: tor-relay
  replicas: 1
  template:
    metadata:
      labels:
        app: tor-relay
    spec:
      containers:
      - name: tor-relay
        image: iamd3vil/tor-relay:v1.0.5
        imagePullPolicy: Always
        ports:
        - containerPort: 9001
        volumeMounts:
        - mountPath: "/var/lib/tor"
          name: tor-volume
        resources:
          limits:
            cpu: "0.4"
          requests:
            cpu: "0.2"
      volumes:
      - name: tor-volume
        persistentVolumeClaim:
          claimName: tor-relay-pvc

---

apiVersion:  v1
kind: Service
metadata:
  name: tor-relay-service
spec:
  selector:
    app: tor-relay
  type: NodePort
  ports:
  - protocol: TCP
    port: 9001
    nodePort: 30111
    targetPort: 9001
